export const ERROR_STATUS_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  UNSUPPORTED_MEDIA_TYPE: 415,
  INTERNAL_SERVER_ERROR: 500,
};

export const ERROR_CODES = {
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  LIMIT_FILE_SIZE: "LIMIT_FILE_SIZE",
};
